
hrNames <- function(names) {
  humanNames = c("4x.count" = "cell number",
                 "4x.ratioMitotic" = "mitotic index",
                 "10x.meanNonmitotic.cell.0.s.area" = "cell area",
                 "4x.countpH3"     = "number of mitotic objects",
                 "4x.isMitotic"    = "number of mitotic nuclei",
                 "4x.areaNucAll"   = "area of nuclei",
                 "4x.areaNucSDAll" = "area of nuclei, stddev",
                 "4x.areapH3All"   = "area of mitotic nuclei",
                 "4x.areapH3SD"    = "area of mitotic nuclei, stddev",
                 "4x.areaNucH1"    = "area of nuclei, bin 1",
                 "4x.areaNucH2"    = "area of nuclei, bin 2",
                 "4x.areaNucH3"    = "area of nuclei, bin 3",
                 "4x.areaNucH4"    = "area of nuclei, bin 4",
                 "4x.areaNucH6"    = "area of nuclei, bin 6",
                 "4x.areaNucH8"    = "area of nuclei, bin 8",
                 "4x.areaNucH9"    = "area of nuclei, bin 9",
                 "4x.areaNucH11"   = "area of nuclei, bin 11",
                 "4x.areaNucQ0.03" = "area of nuclei, 3-percentile",
                 "4x.areaNucQ0.10" = "area of nuclei, 10-percentile",
                 "4x.areaNucQ0.25" = "area of nuclei, 25-percentile",
                 "4x.areaNucQ0.50" = "area of nuclei, median",
                 "4x.areaNucQ0.75" = "area of nuclei, 75-percentile",
                 "4x.areaNucQ0.90" = "area of nuclei, 90-percentile",
                 "4x.areaNucQ0.97" = "area of nuclei, 97-percentile",
                 "4x.intH3pH2"     = "pH3 intensity, bin 2",
                 "4x.intH3pH3"     = "pH3 Intensity, bin 3",
                 "4x.intH3pH4"     = "pH3 intensity, bin 4",
                 "4x.intH3pH5"     = "pH3 intensity, bin 5",
                 "4x.intH3pH6"     = "pH3 intensity, bin 6",
                 "4x.intpH3SD"     = "pH3 intensity, stddev",
                 "4x.intH3pQ0.03"  = "pH3 intensity, 3-percentile",
                 "4x.intNucH2"     = "nuclei intensity, bin 2",
                 "4x.intNucH4"     = "nuclei intensity, bin 4",
                 "4x.intNucH7"     = "nuclei intensity, bin 7",
                 "4x.intNucH9"     = "nuclei intensity, bin 9",
                 "4x.intNucQ0.03"  = "nuclei intensity, 3-percentile",
                 "4x.intNucQ0.97"  = "nuclei intensity, 97-percentile",
                 "10x.meanMitotic.nucleus.DAPI.b.sd" = "nuclei intensity, stddev",
                 "10x.meanNonmitotic.cell.Tub.m.eccentricity"     = "eccentricity (nonmitotic cells)",
                 "10x.meanMitotic.nucleus.DAPI.m.eccentricity"    = "eccentricity (mitotic nuclei)",
                 "10x.meanNonmitotic.nucleus.DAPI.m.eccentricity" = "eccentricity (nonmitotic nuclei)",
                 "10x.meanNonmitotic.nucleus.DAPI.m.majoraxis" = "major axis",
                 "10x.meanMitotic.cell.0.s.perimeter"          = "perimeter",
                 "10x.meanNonmitotic.cell.BDAPITub.b.mean"     = "tubulin intensity",
                 "10x.meanMitotic.cell.Tub.b.sd"               = "tubulin intensity, stddev",
                 "10x.meanNonmitotic.cell.Tub.b.q001"          = "tubulin intensity, 1-percentile",
                 "10x.meanMitotic.cell.0.s.radius.min" = "minimum radius",
                 "4x.LCD1"          = "local cell density 1",
                 "4x.LCD2"          = "local cell density 2",
                 "4x.LCDratio.LCD4" = "local cell density 3")
  res = names
  I = match(names, names(humanNames))
  res[!is.na(I)] = humanNames[I[!is.na(I)]]
  res
}
